version: '3'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresDB:/data/postgres
    env_file:
      - ./.env
  parser:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
volumes:
  postgresDB: